---
dependencies:
  auto_route: ^7.8.4
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  intl: any
  shared_preferences: ^2.2.2
  talker_flutter: ^3.6.0
  cached_network_image: ^3.3.1
description: A new Flutter project.
dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: null
  flutter_gen_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=3.2.2 <4.0.0'
flutter:
  generate: true
  assets:
    - assets/
    - .env

  uses-material-design: true
flutter_gen:
  line_length: 80
  output: lib/gen/
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      class_name: MovieAssets

name: flutter_movie_app
version: 1.0.0+1
