---
dependencies:
  auto_route: ^7.8.4
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.6.0
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  intl: any
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  talker_flutter: ^3.6.0
  cached_network_image: ^3.3.1
  youtube_player_flutter: ^8.1.2
  hive: ^2.2.3
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  formz: ^0.7.0
  geolocator: ^11.0.0
  latlong2: ^0.9.0
  google_maps_flutter: ^2.6.1
  latlng: ^2.0.7
  flutter_polyline_points: ^2.0.0
  location: ^5.0.3
  json_serializable: ^6.7.1
  map_launcher: ^3.2.0
  webview_flutter: ^4.7.0
  share_plus: ^7.2.2
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.2.6
  flutter_staggered_grid_view: ^0.7.0


description: A new Flutter project.
dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: null
  flutter_gen_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
environment:
  sdk: '>=3.2.2 <4.0.0'
flutter:
  generate: true
  assets:
    - assets/
    - assets/images/
    - .env

  uses-material-design: true
flutter_gen:
  line_length: 80
  flutter_svg : true
  output: lib/gen/
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      class_name: MovieAssets

name: flutter_movie_app
version: 1.0.0+1
